
version: '2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    networks:
      docker-elk:
    ports:
     - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    container_name: kibana
    environment:
     - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks:
     - docker-elk
    depends_on:
     - elasticsearch
    ports:
     - "5601:5601"

  server:
    build:
      context: ./server
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./server:/go/src/github.com/user/geomess/server
    ports:
      - "8080:8080"
    links:
      - elasticsearch


  client:
    build:
      context: ./client
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./client/src:/client/src
    ports:
      - "3000:3000"
    depends_on:
     - server

networks:
  docker-elk:
    driver: bridge